"""add llm_usage_events

Revision ID: d17c93a5f2b8
Revises: b3e91c47d208
Create Date: 2026-08-22 00:00:00.000000

Written by hand rather than autogenerated: this environment's autogenerate also
proposes dropping the unmanaged raw-DDL forecast_* tables, which is not
something a migration adding one table should carry (see the note in
e82100c64e7e and alembic/env.py).
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd17c93a5f2b8'
down_revision: Union[str, None] = 'b3e91c47d208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'llm_usage_events',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('user_id', sa.String(length=32), nullable=False),
        sa.Column('project_id', sa.String(length=32), nullable=True),
        sa.Column('purpose', sa.String(length=40), nullable=False),
        sa.Column('provider', sa.String(length=20), nullable=False),
        sa.Column('model', sa.String(length=120), nullable=False),
        sa.Column('prompt_tokens', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('completion_tokens', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('total_tokens', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('latency_ms', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('streamed', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='ok'),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('fallback_depth', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('source', sa.String(length=20), nullable=False, server_default='user'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_llm_usage_events_user_id'), 'llm_usage_events', ['user_id'])
    op.create_index(op.f('ix_llm_usage_events_project_id'), 'llm_usage_events', ['project_id'])
    op.create_index(op.f('ix_llm_usage_events_created_at'), 'llm_usage_events', ['created_at'])
    # The composite the dashboard actually queries on: "this user, this window".
    op.create_index('ix_llm_usage_user_created', 'llm_usage_events', ['user_id', 'created_at'])


def downgrade() -> None:
    op.drop_index('ix_llm_usage_user_created', table_name='llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_events_created_at'), table_name='llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_events_project_id'), table_name='llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_events_user_id'), table_name='llm_usage_events')
    op.drop_table('llm_usage_events')
