"""Deterministic cleaning operators + the measuring apply engine.

This is the execution layer of the cleaning agent. The planner selects and
parameterises operators from ``REGISTRY``; nothing here is generated by an LLM,
so every transformation is deterministic, unit-testable, and re-runnable.

Two rules make the whole thing trustworthy:

1. **Operators never report their own effects.** An operator is a pure
   ``(df, columns, params) -> df`` function. ``apply_step`` diffs the frame
   before and after and *measures* what changed. A buggy operator therefore
   produces a wrong-looking ledger and trips the validator, instead of a
   confident log line that isn't true.

2. **Operators never fabricate values to keep a metric flat.** Parsing
   operators turn genuinely unparseable input into NULL and say so
   (``may_introduce_nulls``). Filling those NULLs is a separate, explicit
   ``impute`` step that the plan has to ask for. The old pipeline instructed
   the LLM to back-fill unparseable dates specifically so the null check would
   stay quiet — that is data fabrication, and it is now structurally
   impossible to do by accident.

Index contract: ``apply_plan`` resets to a clean RangeIndex once, then every
operator must return a frame whose index is a subset of the one it received,
with no duplicates and no new labels. That is what lets ``_diff`` align rows
and count real value changes rather than guessing.
"""

from __future__ import annotations

import re
from typing import Any, Callable

import numpy as np
import pandas as pd

from models.cleaning_ops import (
    CellChange,
    CleaningLedger,
    CleaningStep,
    OperatorSpec,
    ParamSpec,
    StepLedger,
)
from tools.arabic_text import ARABIC_PLACEHOLDERS, normalize_arabic

OperatorFn = Callable[[pd.DataFrame, list[str], dict], pd.DataFrame]

_MAX_SAMPLES = 5

# Strings that mean "missing" regardless of the column's pandas dtype.
NULL_TOKENS: set[str] = (
    {
        "", "-", "--", "?", "??", "n/a", "n.a.", "na", "nan", "none", "null", "nil",
        "unknown", "unspecified", "not available", "not specified", "missing",
        "tbd", "tba", "error", "err", "#n/a", "#value!", "#ref!", "#div/0!",
        "\\n", "<na>", "(blank)", "blank", "empty",
    }
    | {p.lower() for p in ARABIC_PLACEHOLDERS}
    | {normalize_arabic(p).lower() for p in ARABIC_PLACEHOLDERS}
)

# Numeric values conventionally used as "missing" sentinels. Only ever applied
# when the caller names them explicitly — see `replace_sentinels`.
COMMON_SENTINELS: tuple[float, ...] = (-1, -99, -999, -9999, 9999, 99999, -999999, 999999)

_TRUE_TOKENS = {"true", "t", "yes", "y", "1", "1.0", "on", "نعم", "صح", "صحيح"}
_FALSE_TOKENS = {"false", "f", "no", "n", "0", "0.0", "off", "لا", "خطا", "خطأ"}

# Decoration that may legitimately surround a number: currency symbols and
# codes, percent signs, and any flavour of space. Deliberately a closed list —
# stripping "everything that is not a digit" turns the identifier "A1" into 1
# and the date "2024-01-05" into 20240105, silently coercing codes and dates
# into numbers that were never in the data.
_DECORATION_RE = re.compile(
    r"[$€£¥₹﷼%٪\s  ]|\b(?:usd|eur|gbp|egp|sar|aed|kwd|jod|qar|bhd|try|inr)\b"
    r"|ج\.م|ر\.س|د\.إ|د\.ك",
    re.IGNORECASE,
)
# What is left must be a number and nothing else.
_STRICT_NUMBER_RE = re.compile(r"^[+-]?[\d.,]*\d[\d.,]*(?:[eE][+-]?\d+)?$")
# A single trailing comma group of 1-2 digits is a decimal comma, never a
# thousands separator (thousands groups are always exactly three digits).
_DECIMAL_COMMA_RE = re.compile(r"^[+-]?\d+,\d{1,2}$")
_EU_DECIMAL_RE = re.compile(r"^\s*[^\d\-+]*[-+]?\d{1,3}(\.\d{3})+,\d+\s*[^\d]*$")
_US_DECIMAL_RE = re.compile(r"^\s*[^\d\-+]*[-+]?\d{1,3}(,\d{3})+\.\d+\s*[^\d]*$")
_DMY_RE = re.compile(r"^\s*(\d{1,2})[/\-.](\d{1,2})[/\-.](\d{2,4})\s*$")
# Year-first values are unambiguous and must never be touched by `dayfirst`.
_YMD_RE = re.compile(r"^\s*\d{4}[/\-.]\d{1,2}[/\-.]\d{1,2}")

# Excel serial dates (1900 date system) and epoch timestamps, by magnitude.
_EXCEL_SERIAL_RANGE = (20000, 80000)      # 1954-10-03 .. 2118-12-31
_EPOCH_SECONDS_RANGE = (5e8, 4e9)         # 1985 .. 2096
_EPOCH_MILLIS_RANGE = (5e11, 4e12)


# ══════════════════════════════════════════════════════════════════════
# Value-level parsing helpers (pure, dtype-safe, individually testable)
# ══════════════════════════════════════════════════════════════════════


def _as_text(series: pd.Series) -> pd.Series:
    """Object-dtype view of a series' values as stripped strings, with real
    nulls preserved. Works for mixed-dtype columns, which is the whole point:
    the previous implementation gated on ``is_string_dtype`` and therefore
    silently skipped every column that mixed strings with numbers — exactly
    the messiest, most in-need-of-cleaning columns in a real file.
    """
    out = series.astype(object).where(series.notna())
    return out.map(lambda v: v.strip() if isinstance(v, str) else v)


def null_token_mask(series: pd.Series) -> pd.Series:
    """Boolean mask of values that are placeholder-for-missing strings.

    dtype-agnostic by construction — a column holding ``["UNKNOWN", 5, 3,
    "N/A", 7]`` is object dtype, and this still finds both placeholders.
    """
    text = _as_text(series)
    return text.map(
        lambda v: isinstance(v, str) and normalize_arabic(v).casefold() in NULL_TOKENS
    ).fillna(False).astype(bool)


def infer_decimal_separator(series: pd.Series) -> str:
    """Infer ``','`` (European: 1.299,00) or ``'.'`` (Anglo: 1,299.00) for a
    column, by counting values that can only be read one way. Defaults to
    ``'.'`` when nothing is decisive."""
    text = _as_text(series).dropna().astype(str)
    if text.empty:
        return "."
    eu = int(text.map(lambda v: bool(_EU_DECIMAL_RE.match(v))).sum())
    us = int(text.map(lambda v: bool(_US_DECIMAL_RE.match(v))).sum())
    return "," if eu > us else "."


def parse_numeric_series(
    series: pd.Series,
    *,
    decimal: str | None = None,
    percent_to_fraction: bool = True,
) -> pd.Series:
    """Coerce a messy money/quantity column to float.

    Handles currency symbols and codes, thousands separators in either
    convention, percent signs, accounting-style ``(1,234)`` negatives, and the
    Unicode minus. Anything genuinely unparseable becomes NaN — never a guess.
    """
    if pd.api.types.is_numeric_dtype(series) and not pd.api.types.is_bool_dtype(series):
        return series.astype("float64")

    sep = decimal or infer_decimal_separator(series)
    text = _as_text(series)

    def _one(value: Any) -> float:
        if value is None or (not isinstance(value, str) and pd.isna(value)):
            return np.nan
        if isinstance(value, bool):
            return np.nan
        if isinstance(value, (int, float, np.integer, np.floating)):
            return float(value)

        raw = str(value).strip().replace("−", "-").replace(" ", " ")
        if not raw or normalize_arabic(raw).casefold() in NULL_TOKENS:
            return np.nan

        negative = False
        if raw.startswith("(") and raw.endswith(")"):
            negative, raw = True, raw[1:-1].strip()
        is_percent = "%" in raw or "٪" in raw

        cleaned = _DECORATION_RE.sub("", raw).strip()
        # Anything still carrying a letter, an internal sign or a stray symbol
        # is not a number — it is a code, a date, or free text. Reject it
        # outright rather than salvaging digits out of it.
        if not _STRICT_NUMBER_RE.match(cleaned):
            return np.nan

        if sep == "," or _DECIMAL_COMMA_RE.match(cleaned):
            cleaned = cleaned.replace(".", "").replace(",", ".")
        else:
            cleaned = cleaned.replace(",", "")

        try:
            number = float(cleaned)
        except ValueError:
            return np.nan

        if is_percent and percent_to_fraction:
            number /= 100.0
        return -number if negative else number

    return pd.Series([_one(v) for v in text], index=series.index, dtype="float64")


def infer_dayfirst(series: pd.Series) -> bool | None:
    """Resolve the DD/MM vs MM/DD ambiguity from the data itself.

    Returns True (day first), False (month first), or ``None`` when the column
    is genuinely ambiguous — every value parses both ways, so no amount of
    inspection can decide. Callers surface ``None`` as a warning rather than
    silently picking, because guessing wrong shifts up to 12/31 of the rows to
    the wrong month and nothing downstream would ever notice.
    """
    text = _as_text(series).dropna().astype(str)
    first_gt_12 = second_gt_12 = 0
    for value in text:
        m = _DMY_RE.match(value)
        if not m:
            continue
        a, b = int(m.group(1)), int(m.group(2))
        if a > 12 >= b:
            first_gt_12 += 1
        elif b > 12 >= a:
            second_gt_12 += 1
    if first_gt_12 and not second_gt_12:
        return True
    if second_gt_12 and not first_gt_12:
        return False
    if first_gt_12 and second_gt_12:
        return None  # internally contradictory — two formats mixed in one column
    # No value has a component above 12: every date parses both ways. If the
    # column contains slash-style dates at all, that is genuinely undecidable.
    has_ambiguous = any(_DMY_RE.match(v) for v in text)
    return None if has_ambiguous else False


def parse_datetime_series(
    series: pd.Series, *, dayfirst: bool | None = None, fmt: str | None = None
) -> pd.Series:
    """Coerce a column to datetime64, handling mixed string formats, Excel
    serial numbers and epoch timestamps. Unparseable values become NaT."""
    if pd.api.types.is_datetime64_any_dtype(series):
        return series

    if fmt:
        return pd.to_datetime(_as_text(series), format=fmt, errors="coerce")

    # Numeric columns are serials or epochs, not date strings.
    numeric = pd.to_numeric(_as_text(series), errors="coerce")
    non_null = numeric.dropna()
    if len(non_null) and numeric.notna().sum() >= series.notna().sum() * 0.9:
        median = float(non_null.abs().median())
        if _EXCEL_SERIAL_RANGE[0] <= median <= _EXCEL_SERIAL_RANGE[1]:
            return pd.to_datetime(numeric, unit="D", origin="1899-12-30", errors="coerce")
        if _EPOCH_MILLIS_RANGE[0] <= median <= _EPOCH_MILLIS_RANGE[1]:
            return pd.to_datetime(numeric, unit="ms", errors="coerce")
        if _EPOCH_SECONDS_RANGE[0] <= median <= _EPOCH_SECONDS_RANGE[1]:
            return pd.to_datetime(numeric, unit="s", errors="coerce")

    resolved = infer_dayfirst(series) if dayfirst is None else dayfirst
    text = _as_text(series)

    # Parse year-first values separately. `dayfirst` is inferred from the
    # slash-style values in the column, and applying it to an ISO string
    # silently reinterprets 2024-01-05 as 5 January vs 1 May — a one-line
    # setting that moves up to 11/12 of the rows into the wrong month with
    # nothing downstream able to notice.
    is_ymd = text.map(lambda v: bool(_YMD_RE.match(v)) if isinstance(v, str) else False)
    parsed = pd.to_datetime(
        text.where(~is_ymd), errors="coerce", dayfirst=bool(resolved), format="mixed"
    )
    if is_ymd.any():
        iso = pd.to_datetime(text.where(is_ymd), errors="coerce", format="mixed")
        parsed = parsed.fillna(iso)
    return parsed


def parse_boolean_series(series: pd.Series) -> pd.Series:
    """Coerce Y/N, yes/no, true/false, 1/0 (and Arabic نعم/لا) to nullable
    boolean. Unrecognised values become NA."""
    if pd.api.types.is_bool_dtype(series):
        return series.astype("boolean")

    def _one(value: Any) -> Any:
        if value is None or (not isinstance(value, str) and pd.isna(value)):
            return pd.NA
        if isinstance(value, (bool, np.bool_)):
            return bool(value)
        token = normalize_arabic(str(value)).strip().casefold()
        if token in _TRUE_TOKENS:
            return True
        if token in _FALSE_TOKENS:
            return False
        return pd.NA

    return pd.Series([_one(v) for v in series], index=series.index, dtype="boolean")


def category_key(value: Any) -> str:
    """Normalized grouping key for near-duplicate category detection:
    case-folded, whitespace-collapsed, punctuation-stripped, Arabic-normalized.
    ``"Cairo"``, ``"cairo "`` and ``"CAIRO"`` share a key; ``"Cairo"`` and
    ``"Giza"`` do not — so merging on this key can never fuse two genuinely
    different categories.
    """
    text = normalize_arabic(str(value)).casefold()
    text = re.sub(r"[^\w\s]", "", text, flags=re.UNICODE)
    return re.sub(r"\s+", " ", text).strip()


# ══════════════════════════════════════════════════════════════════════
# Operators — pure (df, columns, params) -> df
# ══════════════════════════════════════════════════════════════════════


def _targets(df: pd.DataFrame, columns: list[str]) -> list[str]:
    return [c for c in columns if c in df.columns]


def op_standardize_null_placeholders(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    df = df.copy()
    for col in _targets(df, columns):
        mask = null_token_mask(df[col])
        if not mask.any():
            continue
        try:
            df[col] = df[col].mask(mask)
        except (TypeError, ValueError):
            # Mixed-dtype columns can't always hold their own NA — fall back
            # to object, which always can.
            df[col] = df[col].astype(object).mask(mask, other=None)
    return df


def op_replace_sentinels(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    values = params.get("values") or list(COMMON_SENTINELS)
    wanted = {float(v) for v in values}
    df = df.copy()
    for col in _targets(df, columns):
        numeric = pd.to_numeric(_as_text(df[col]), errors="coerce")
        mask = numeric.isin(wanted).fillna(False)
        if mask.any():
            df[col] = df[col].mask(mask)
    return df


def op_trim_whitespace(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    df = df.copy()
    for col in _targets(df, columns):
        df[col] = df[col].map(
            lambda v: re.sub(r"\s+", " ", v).strip() if isinstance(v, str) else v
        )
    return df


def op_parse_numeric(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    df = df.copy()
    for col in _targets(df, columns):
        df[col] = parse_numeric_series(
            df[col],
            decimal=params.get("decimal"),
            percent_to_fraction=bool(params.get("percent_to_fraction", True)),
        )
    return df


def op_parse_datetime(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    df = df.copy()
    for col in _targets(df, columns):
        df[col] = parse_datetime_series(
            df[col], dayfirst=params.get("dayfirst"), fmt=params.get("format")
        )
    return df


def op_parse_boolean(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    df = df.copy()
    for col in _targets(df, columns):
        df[col] = parse_boolean_series(df[col])
    return df


def op_cast_integer(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    """Narrow a float column back to nullable Int64 when every value is whole.

    Counterpart to the old blanket ``astype('float64')`` widening, which turned
    every integer id in the dataset into ``1001.0`` — including columns with no
    nulls and nothing to fix — and carried that representation into the DDL and
    into every join key.
    """
    df = df.copy()
    for col in _targets(df, columns):
        numeric = pd.to_numeric(_as_text(df[col]), errors="coerce")
        finite = numeric.dropna()
        if finite.empty or not bool(np.isfinite(finite).all()) or not bool((finite % 1 == 0).all()):
            continue
        df[col] = numeric.astype("Int64")
    return df


def op_impute(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    strategy = str(params.get("strategy", "median")).lower()
    max_missing_pct = float(params.get("max_missing_pct", 50.0))
    df = df.copy()

    for col in _targets(df, columns):
        series = df[col]
        if series.isna().mean() * 100 > max_missing_pct:
            # Imputing a majority-missing column manufactures the column.
            continue
        if strategy == "constant":
            filled = series.fillna(params.get("value"))
        elif strategy == "ffill":
            filled = series.ffill()
        elif strategy == "bfill":
            filled = series.bfill()
        elif strategy == "mode":
            modes = series.dropna().mode()
            filled = series.fillna(modes.iloc[0]) if len(modes) else series
        elif strategy in ("mean", "median"):
            numeric = pd.to_numeric(series, errors="coerce")
            if numeric.dropna().empty:
                continue
            value = numeric.mean() if strategy == "mean" else numeric.median()
            filled = numeric.fillna(value)
        else:
            continue
        df[col] = filled
    return df


def op_flag_missing(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    df = df.copy()
    for col in _targets(df, columns):
        df[f"{col}__is_missing"] = df[col].isna()
    return df


def op_harmonize_case(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    style = str(params.get("style", "title")).lower()
    fn = {"lower": str.lower, "upper": str.upper, "title": str.title}.get(style, str.title)
    df = df.copy()
    for col in _targets(df, columns):
        df[col] = df[col].map(lambda v: fn(v) if isinstance(v, str) else v)
    return df


def op_harmonize_categories(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    """Fold spelling/case/whitespace variants of the same category onto its most
    common spelling. Only values sharing a normalized key are ever merged."""
    df = df.copy()
    for col in _targets(df, columns):
        series = df[col]
        text = series.where(series.map(lambda v: isinstance(v, str)))
        if text.dropna().empty:
            continue
        keys = text.map(lambda v: category_key(v) if isinstance(v, str) else None)
        canonical: dict[str, str] = {}
        for key, group in text.dropna().groupby(keys.dropna()):
            counts = group.value_counts()
            top = counts.index[0]
            if len(counts) > 1:
                canonical[str(key)] = str(top)
        if canonical:
            df[col] = series.map(
                lambda v: canonical.get(category_key(v), v) if isinstance(v, str) else v
            )
    return df


def op_replace_values(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    mapping = params.get("mapping") or {}
    if not isinstance(mapping, dict) or not mapping:
        return df
    df = df.copy()
    for col in _targets(df, columns):
        df[col] = df[col].map(lambda v: mapping.get(str(v), v) if not pd.isna(v) else v)
    return df


def op_drop_duplicate_rows(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    subset = _targets(df, columns) or None
    return df.drop_duplicates(subset=subset, keep=params.get("keep", "first"))


def op_drop_duplicate_keys(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    subset = _targets(df, columns)
    if not subset:
        return df
    return df.drop_duplicates(subset=subset, keep=params.get("keep", "first"))


def op_flag_duplicate_keys(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    subset = _targets(df, columns)
    if not subset:
        return df
    df = df.copy()
    name = params.get("flag_column") or f"{'_'.join(subset)}__is_duplicate_key"
    df[name] = df.duplicated(subset=subset, keep=False)
    return df


def op_drop_column(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    targets = _targets(df, columns)
    return df.drop(columns=targets) if targets else df


def _outlier_mask(series: pd.Series, method: str, factor: float) -> pd.Series:
    numeric = pd.to_numeric(series, errors="coerce")
    finite = numeric.dropna()
    if len(finite) < 4:
        return pd.Series(False, index=series.index)
    if method == "zscore":
        std = finite.std()
        if not std:
            return pd.Series(False, index=series.index)
        return ((numeric - finite.mean()).abs() / std > factor).fillna(False)
    if method == "modified_zscore":
        median = finite.median()
        mad = (finite - median).abs().median()
        if not mad:
            return pd.Series(False, index=series.index)
        return ((0.6745 * (numeric - median) / mad).abs() > factor).fillna(False)
    q1, q3 = finite.quantile(0.25), finite.quantile(0.75)
    iqr = q3 - q1
    if not iqr:
        return pd.Series(False, index=series.index)
    return ((numeric < q1 - factor * iqr) | (numeric > q3 + factor * iqr)).fillna(False)


def op_flag_outliers(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    """Mark statistical outliers in a new boolean column. Deliberately does not
    modify the values: on skewed business data (order value, revenue) an IQR
    fence flags a long tail of legitimate large orders, and capping them
    rewrites real observations into ones that never occurred."""
    method = str(params.get("method", "iqr")).lower()
    factor = float(params.get("factor", 1.5 if method == "iqr" else 3.0))
    df = df.copy()
    for col in _targets(df, columns):
        df[f"{col}__is_outlier"] = _outlier_mask(df[col], method, factor)
    return df


def op_clip_range(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    """Clamp values to a *domain* bound the plan states explicitly (e.g. a
    discount percentage cannot exceed 100). Not a statistical fence."""
    low, high = params.get("min"), params.get("max")
    if low is None and high is None:
        return df
    df = df.copy()
    for col in _targets(df, columns):
        numeric = pd.to_numeric(df[col], errors="coerce")
        if numeric.dropna().empty:
            continue
        df[col] = numeric.clip(lower=low, upper=high)
    return df


def op_flag_range_violation(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    low, high = params.get("min"), params.get("max")
    df = df.copy()
    for col in _targets(df, columns):
        numeric = pd.to_numeric(df[col], errors="coerce")
        bad = pd.Series(False, index=df.index)
        if low is not None:
            bad |= (numeric < float(low)).fillna(False)
        if high is not None:
            bad |= (numeric > float(high)).fillna(False)
        df[f"{col}__out_of_range"] = bad
    return df


def op_flag_arithmetic_violation(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    """Flag rows where a stated cross-column identity fails, e.g.
    ``line_total = quantity × unit_price``. These rows are real data errors —
    the profiler already detects such identities; nothing used to act on them.
    """
    left, right = params.get("left"), params.get("right")
    result = params.get("result") or (columns[0] if columns else None)
    operator = str(params.get("operator", "*"))
    tolerance = float(params.get("tolerance", 0.01))
    if not (left and right and result) or not all(c in df.columns for c in (left, right, result)):
        return df

    df = df.copy()
    a = pd.to_numeric(df[left], errors="coerce")
    b = pd.to_numeric(df[right], errors="coerce")
    c = pd.to_numeric(df[result], errors="coerce")
    expected = a * b if operator == "*" else a + b if operator == "+" else a - b
    denominator = c.abs().where(c.abs() > 0, other=np.nan)
    relative = (expected - c).abs() / denominator
    mismatch = (relative > tolerance).fillna(False) & expected.notna() & c.notna()
    df[f"{result}__mismatch"] = mismatch
    return df


def op_recompute_arithmetic(df: pd.DataFrame, columns: list[str], params: dict) -> pd.DataFrame:
    """Overwrite a derived column from its inputs where the identity fails.
    Opt-in: only correct when the inputs are known to be the source of truth."""
    left, right = params.get("left"), params.get("right")
    result = params.get("result") or (columns[0] if columns else None)
    operator = str(params.get("operator", "*"))
    tolerance = float(params.get("tolerance", 0.01))
    if not (left and right and result) or not all(c in df.columns for c in (left, right, result)):
        return df

    df = df.copy()
    a = pd.to_numeric(df[left], errors="coerce")
    b = pd.to_numeric(df[right], errors="coerce")
    c = pd.to_numeric(df[result], errors="coerce")
    expected = a * b if operator == "*" else a + b if operator == "+" else a - b
    denominator = c.abs().where(c.abs() > 0, other=np.nan)
    mismatch = (
        ((expected - c).abs() / denominator > tolerance).fillna(False)
        & expected.notna()
        & c.notna()
    )
    df[result] = c.mask(mismatch, expected)
    return df


# ══════════════════════════════════════════════════════════════════════
# Registry
# ══════════════════════════════════════════════════════════════════════


def _spec(name: str, summary: str, params: list[ParamSpec] | None = None, **flags) -> OperatorSpec:
    return OperatorSpec(name=name, summary=summary, params=params or [], **flags)


_P = ParamSpec

REGISTRY: dict[str, tuple[OperatorSpec, OperatorFn]] = {
    "standardize_null_placeholders": (
        _spec(
            "standardize_null_placeholders",
            "Convert placeholder strings (UNKNOWN, N/A, ERROR, -, غير معروف …) to real NULLs.",
            accepts_multiple_columns=True, may_introduce_nulls=True, may_change_dtype=True,
        ),
        op_standardize_null_placeholders,
    ),
    "replace_sentinels": (
        _spec(
            "replace_sentinels",
            "Convert numeric missing-data sentinels (-999, 9999 …) to NULL.",
            [_P(name="values", type="list", description="Sentinel numbers to treat as missing")],
            accepts_multiple_columns=True, may_introduce_nulls=True, may_change_dtype=True,
        ),
        op_replace_sentinels,
    ),
    "trim_whitespace": (
        _spec(
            "trim_whitespace",
            "Strip leading/trailing whitespace and collapse internal runs of spaces.",
            accepts_multiple_columns=True,
        ),
        op_trim_whitespace,
    ),
    "parse_numeric": (
        _spec(
            "parse_numeric",
            "Convert a text column to numbers, handling currency symbols, thousands "
            "separators, percentages and (1,234) negatives. Unparseable values become NULL.",
            [
                _P(name="decimal", type="str", choices=[".", ","],
                   description="Decimal separator; inferred from the data when omitted"),
                _P(name="percent_to_fraction", type="bool", default=True,
                   description="Divide percent-signed values by 100"),
            ],
            accepts_multiple_columns=True, may_introduce_nulls=True, may_change_dtype=True,
        ),
        op_parse_numeric,
    ),
    "parse_datetime": (
        _spec(
            "parse_datetime",
            "Convert a column to real dates, handling mixed formats, Excel serial numbers "
            "and epoch timestamps. Unparseable values become NULL and are reported.",
            [
                _P(name="dayfirst", type="bool",
                   description="Force DD/MM (true) or MM/DD (false); inferred when omitted"),
                _P(name="format", type="str", description="Explicit strptime format"),
            ],
            accepts_multiple_columns=True, may_introduce_nulls=True, may_change_dtype=True,
        ),
        op_parse_datetime,
    ),
    "parse_boolean": (
        _spec(
            "parse_boolean",
            "Convert Y/N, yes/no, true/false, 1/0 to a real boolean column.",
            accepts_multiple_columns=True, may_introduce_nulls=True, may_change_dtype=True,
        ),
        op_parse_boolean,
    ),
    "cast_integer": (
        _spec(
            "cast_integer",
            "Store a whole-number column as an integer instead of 1001.0-style floats.",
            accepts_multiple_columns=True, may_change_dtype=True,
        ),
        op_cast_integer,
    ),
    "impute": (
        _spec(
            "impute",
            "Fill missing values using an explicit strategy. Refuses columns that are "
            "more than max_missing_pct empty, where filling would invent the column.",
            [
                _P(name="strategy", type="str", required=True,
                   choices=["median", "mean", "mode", "constant", "ffill", "bfill"]),
                _P(name="value", type="str", description="Fill value when strategy=constant"),
                _P(name="max_missing_pct", type="float", default=50.0),
            ],
            accepts_multiple_columns=True, may_change_dtype=True,
            may_fill_nulls=True,
            # Imputation fills blanks and nothing else. Without this, naming a
            # column in a "fill the missing values" step would license
            # rescaling or overwriting every value already in it.
            may_rewrite_values=False,
        ),
        op_impute,
    ),
    "flag_missing": (
        _spec(
            "flag_missing",
            "Add a <column>__is_missing indicator so downstream analysis can see where "
            "data was absent rather than silently treating an imputed value as observed.",
            accepts_multiple_columns=True, may_add_columns=True,
            may_rewrite_values=False,
        ),
        op_flag_missing,
    ),
    "harmonize_case": (
        _spec(
            "harmonize_case",
            "Apply a consistent letter case to a categorical column.",
            [_P(name="style", type="str", default="title", choices=["lower", "upper", "title"])],
            accepts_multiple_columns=True,
        ),
        op_harmonize_case,
    ),
    "harmonize_categories": (
        _spec(
            "harmonize_categories",
            "Merge spelling/case/spacing variants of the same category onto its most "
            "common spelling (Cairo / cairo / CAIRO -> Cairo). Never merges different values.",
            accepts_multiple_columns=True,
        ),
        op_harmonize_categories,
    ),
    "replace_values": (
        _spec(
            "replace_values",
            "Apply an explicit old -> new value mapping.",
            [_P(name="mapping", type="dict", required=True)],
            accepts_multiple_columns=True,
            may_fill_nulls=True,
        ),
        op_replace_values,
    ),
    "drop_duplicate_rows": (
        _spec(
            "drop_duplicate_rows",
            "Remove rows that are exact duplicates across every column.",
            [_P(name="keep", type="str", default="first", choices=["first", "last"])],
            requires_column=False, accepts_multiple_columns=True, may_remove_rows=True,
            may_rewrite_values=False,
        ),
        op_drop_duplicate_rows,
    ),
    "drop_duplicate_keys": (
        _spec(
            "drop_duplicate_keys",
            "Remove rows repeating an existing business key (e.g. the same order_id twice).",
            [_P(name="keep", type="str", default="first", choices=["first", "last"])],
            accepts_multiple_columns=True, may_remove_rows=True,
            may_rewrite_values=False,
        ),
        op_drop_duplicate_keys,
    ),
    "flag_duplicate_keys": (
        _spec(
            "flag_duplicate_keys",
            "Mark rows sharing a business key without deleting them — the safe first move "
            "when the duplicates may carry different data.",
            [_P(name="flag_column", type="str")],
            accepts_multiple_columns=True, may_add_columns=True,
            may_rewrite_values=False,
        ),
        op_flag_duplicate_keys,
    ),
    "drop_column": (
        _spec(
            "drop_column",
            "Remove a column that is entirely empty or entirely constant.",
            accepts_multiple_columns=True, may_drop_columns=True,
            may_rewrite_values=False,
        ),
        op_drop_column,
    ),
    "flag_outliers": (
        _spec(
            "flag_outliers",
            "Mark statistical outliers in a new <column>__is_outlier column, leaving the "
            "values themselves untouched.",
            [
                _P(name="method", type="str", default="iqr",
                   choices=["iqr", "zscore", "modified_zscore"]),
                _P(name="factor", type="float", default=1.5),
            ],
            accepts_multiple_columns=True, may_add_columns=True,
            may_rewrite_values=False,
        ),
        op_flag_outliers,
    ),
    "clip_range": (
        _spec(
            "clip_range",
            "Clamp values to a stated real-world bound (e.g. a percentage to 0-100). Use "
            "only for genuine domain limits, never as a statistical outlier fence.",
            [_P(name="min", type="float"), _P(name="max", type="float")],
            accepts_multiple_columns=True, may_change_dtype=True,
        ),
        op_clip_range,
    ),
    "flag_range_violation": (
        _spec(
            "flag_range_violation",
            "Mark values outside a valid business range (negative quantity, discount > 100%).",
            [_P(name="min", type="float"), _P(name="max", type="float")],
            accepts_multiple_columns=True, may_add_columns=True,
            may_rewrite_values=False,
        ),
        op_flag_range_violation,
    ),
    "flag_arithmetic_violation": (
        _spec(
            "flag_arithmetic_violation",
            "Mark rows where a cross-column identity fails, e.g. total = quantity x unit_price.",
            [
                _P(name="left", type="str", required=True),
                _P(name="right", type="str", required=True),
                _P(name="result", type="str", required=True),
                _P(name="operator", type="str", default="*", choices=["*", "+", "-"]),
                _P(name="tolerance", type="float", default=0.01),
            ],
            requires_column=False, may_add_columns=True,
            may_rewrite_values=False,
        ),
        op_flag_arithmetic_violation,
    ),
    "recompute_arithmetic": (
        _spec(
            "recompute_arithmetic",
            "Recompute a derived column from its inputs where the identity fails. Only when "
            "the input columns are the source of truth.",
            [
                _P(name="left", type="str", required=True),
                _P(name="right", type="str", required=True),
                _P(name="result", type="str", required=True),
                _P(name="operator", type="str", default="*", choices=["*", "+", "-"]),
                _P(name="tolerance", type="float", default=0.01),
            ],
            requires_column=False, may_change_dtype=True,
            may_fill_nulls=True,
        ),
        op_recompute_arithmetic,
    ),
}

# Operators that are safe to run on a cross-table join key. Anything else
# changing a key column's representation can orphan rows in the other table —
# the exact failure mode behind past ForeignKeyViolation saves.
KEY_SAFE_OPS: frozenset[str] = frozenset({
    "trim_whitespace",
    "standardize_null_placeholders",
    "flag_missing",
    "flag_duplicate_keys",
    "flag_outliers",
    "flag_range_violation",
    "drop_duplicate_rows",
    "drop_duplicate_keys",
})


# Safe execution order. Placeholders and sentinels become NULL first so parsing
# sees real nulls; parsing precedes anything that reads the values as numbers or
# dates; row removal precedes flagging so flags describe surviving rows; and
# imputation runs LAST so it fills only what genuinely remains missing.
#
# The dedupe-before-impute ordering is not cosmetic. Imputing first turns
# [1.0, NULL, 1.0] into [1.0, 1.0, 1.0], manufacturing a duplicate that was
# never in the source; the dedupe step then deletes a row that was genuinely
# distinct. The old pipeline generated code in whatever order the plan happened
# to list, so this silently destroyed real records.
OP_EXECUTION_ORDER: dict[str, int] = {
    "standardize_null_placeholders": 10,
    "replace_sentinels": 20,
    "trim_whitespace": 30,
    "parse_numeric": 40,
    "parse_datetime": 41,
    "parse_boolean": 42,
    "cast_integer": 43,
    "harmonize_case": 50,
    "harmonize_categories": 51,
    "replace_values": 52,
    "drop_column": 60,
    "drop_duplicate_rows": 70,
    "drop_duplicate_keys": 71,
    "flag_duplicate_keys": 80,
    "flag_range_violation": 81,
    "flag_arithmetic_violation": 82,
    "flag_outliers": 83,
    "recompute_arithmetic": 84,
    "clip_range": 85,
    "flag_missing": 90,
    "impute": 95,
}


def order_steps(steps: list[CleaningStep]) -> list[CleaningStep]:
    """Sort a plan into the safe execution order and renumber it.

    Applied to every plan regardless of origin. A planner LLM has no reason to
    know that de-duplication must precede imputation, and asking it to get the
    ordering right is a needless dependency on the model behaving — the
    ordering is a property of the operators, so the system owns it.

    Free-text steps sort last: they run as generated code after the operators,
    on the already-cleaned frame.
    """
    ordered = sorted(
        steps, key=lambda s: OP_EXECUTION_ORDER.get(s.op, 999 if not s.op else 100)
    )
    for position, step in enumerate(ordered, start=1):
        step.id = str(position)
    return ordered


def operator_catalog() -> str:
    """Render the registry as the operator menu shown to the planner LLM."""
    lines = []
    for spec, _ in REGISTRY.values():
        params = ", ".join(
            f"{p.name}"
            + (f"={p.default!r}" if p.default is not None else "")
            + ("*" if p.required else "")
            + (f" one of {p.choices}" if p.choices else "")
            for p in spec.params
        )
        lines.append(f"- {spec.name}({params or 'no params'}): {spec.summary}")
    return "\n".join(lines)


def validate_step(step: CleaningStep, df_columns: list[str] | None = None) -> str | None:
    """Check a planned step against the registry *before* running anything.
    Returns an error string, or None when the step is well-formed."""
    entry = REGISTRY.get(step.op)
    if entry is None:
        return f"unknown operator '{step.op}'"
    spec, _ = entry

    if spec.requires_column and not step.columns:
        return f"operator '{step.op}' requires at least one target column"
    if step.columns and not spec.accepts_multiple_columns and len(step.columns) > 1:
        return f"operator '{step.op}' accepts a single column, got {len(step.columns)}"
    if df_columns is not None:
        missing = [c for c in step.columns if c not in df_columns]
        if missing and len(missing) == len(step.columns):
            return f"column(s) {missing} are not in the table"

    known = {p.name for p in spec.params}
    unknown = set(step.params) - known
    if unknown:
        return f"operator '{step.op}' got unknown parameter(s) {sorted(unknown)}"
    for p in spec.params:
        if p.required and step.params.get(p.name) is None:
            return f"operator '{step.op}' requires parameter '{p.name}'"
        value = step.params.get(p.name)
        if value is not None and p.choices and value not in p.choices:
            return f"parameter '{p.name}' must be one of {p.choices}, got {value!r}"
    return None


# ══════════════════════════════════════════════════════════════════════
# Apply engine — measures, never trusts
# ══════════════════════════════════════════════════════════════════════


def _changed_mask(before: pd.DataFrame, after: pd.DataFrame) -> pd.DataFrame:
    """Elementwise "did this cell's value change" over aligned frames.
    NaN==NaN counts as unchanged; a pure dtype change (1001 -> 1001.0) does not
    count as a value change and is recorded separately."""
    before_null, after_null = before.isna(), after.isna()
    equal = pd.DataFrame(False, index=before.index, columns=before.columns)
    for col in before.columns:
        live = ~(before_null[col] | after_null[col])
        if not live.any():
            continue
        left, right = before.loc[live, col], after.loc[live, col]
        try:
            equal.loc[live, col] = np.asarray(left.to_numpy() == right.to_numpy(), dtype=bool)
        except (TypeError, ValueError):
            equal.loc[live, col] = (
                left.astype(str).to_numpy() == right.astype(str).to_numpy()
            )
    both_null = before_null & after_null
    return ~both_null & ~equal


def _sample_changes(
    before: pd.DataFrame, after: pd.DataFrame, changed: pd.DataFrame
) -> list[CellChange]:
    samples: list[CellChange] = []
    for col in changed.columns:
        for idx in changed.index[changed[col]][:2]:
            samples.append(
                CellChange(
                    row=str(idx), column=str(col),
                    before=_jsonable(before.at[idx, col]),
                    after=_jsonable(after.at[idx, col]),
                )
            )
            if len(samples) >= _MAX_SAMPLES:
                return samples
    return samples


def _jsonable(value: Any) -> Any:
    if value is None or (not isinstance(value, str) and pd.isna(value)):
        return None
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, (np.bool_,)):
        return bool(value)
    if isinstance(value, (pd.Timestamp,)):
        return value.isoformat()
    return value if isinstance(value, (int, float, bool, str)) else str(value)


def _summarize(ledger: StepLedger) -> str:
    """One log line, built entirely from measured counts."""
    where = ", ".join(ledger.columns) if ledger.columns else "the table"
    bits: list[str] = []
    if ledger.rows_removed:
        bits.append(f"removed {ledger.rows_removed} row(s)")
    if ledger.nulls_filled:
        bits.append(f"filled {ledger.nulls_filled} missing value(s)")
    if ledger.nulls_introduced:
        bits.append(f"set {ledger.nulls_introduced} unparseable/placeholder value(s) to NULL")
    changed_only = ledger.cells_changed - ledger.nulls_filled - ledger.nulls_introduced
    if changed_only > 0:
        bits.append(f"rewrote {changed_only} value(s)")
    if ledger.columns_added:
        bits.append(f"added column(s) {', '.join(ledger.columns_added)}")
    if ledger.columns_dropped:
        bits.append(f"dropped column(s) {', '.join(ledger.columns_dropped)}")
    if ledger.dtype_changes:
        bits.append(
            "changed type of "
            + ", ".join(f"{c} -> {t}" for c, t in ledger.dtype_changes.items())
        )
    if not bits:
        return f"{ledger.op} on {where}: no change needed"
    return f"{ledger.op} on {where}: " + "; ".join(bits)


def apply_step(
    df: pd.DataFrame, step: CleaningStep, *, protected_columns: set[str] | None = None
) -> tuple[pd.DataFrame, StepLedger]:
    """Run one typed step and measure exactly what it did.

    On any operator error the original frame is returned untouched and the
    failure is recorded — one bad step never corrupts the run or halts the
    remaining steps.
    """
    protected = protected_columns or set()
    ledger = StepLedger(
        step_id=step.id, op=step.op, columns=list(step.columns),
        params=dict(step.params), rows_before=len(df), rows_after=len(df),
    )

    error = validate_step(step, list(df.columns))
    if error:
        ledger.applied = False
        ledger.error = error
        ledger.summary = f"[failed] {step.op}: {error}"
        return df, ledger

    unsafe_keys = sorted(set(step.columns) & protected)
    if unsafe_keys and step.op not in KEY_SAFE_OPS:
        ledger.applied = False
        ledger.skipped_reason = (
            f"'{step.op}' would change the representation of join key(s) "
            f"{unsafe_keys}, which can orphan rows in the related table"
        )
        ledger.summary = f"[skipped] {step.op}: {ledger.skipped_reason}"
        return df, ledger

    _, fn = REGISTRY[step.op]
    try:
        result = fn(df, list(step.columns), dict(step.params))
    except Exception as exc:  # operator bug or hostile data — never fatal
        ledger.applied = False
        ledger.error = f"{type(exc).__name__}: {exc}"
        ledger.summary = f"[failed] {step.op}: {ledger.error}"
        return df, ledger

    if not isinstance(result, pd.DataFrame):
        ledger.applied = False
        ledger.error = f"operator returned {type(result).__name__}, not a DataFrame"
        ledger.summary = f"[failed] {step.op}: {ledger.error}"
        return df, ledger

    # The result's index must be the input's index with rows only removed —
    # same labels, same order. Anything else means rows were reordered,
    # relabelled or invented, and every value-level comparison below would then
    # be aligning the wrong rows against each other.
    expected_index = df.index[df.index.isin(result.index)]
    if result.index.has_duplicates or not result.index.equals(expected_index):
        ledger.applied = False
        ledger.error = (
            "operator broke the row-identity contract: the returned rows are not the "
            "input rows in their original order"
        )
        ledger.summary = f"[failed] {step.op}: {ledger.error}"
        return df, ledger

    # ── Measure ────────────────────────────────────────────────────────
    ledger.rows_after = len(result)
    ledger.rows_removed = max(0, len(df) - len(result))
    ledger.rows_added = max(0, len(result) - len(df))
    ledger.columns_added = [c for c in result.columns if c not in df.columns]
    ledger.columns_dropped = [c for c in df.columns if c not in result.columns]

    common_idx = df.index.intersection(result.index)
    common_cols = [c for c in df.columns if c in result.columns]
    if len(common_idx) and common_cols:
        before = df.loc[common_idx, common_cols]
        after = result.loc[common_idx, common_cols]
        changed = _changed_mask(before, after)
        ledger.cells_changed = int(changed.to_numpy().sum())
        before_null, after_null = before.isna(), after.isna()
        ledger.nulls_filled = int((before_null & ~after_null).to_numpy().sum())
        ledger.nulls_introduced = int((~before_null & after_null).to_numpy().sum())
        ledger.samples = _sample_changes(before, after, changed)
        ledger.dtype_changes = {
            str(c): str(result[c].dtype)
            for c in common_cols
            if str(df[c].dtype) != str(result[c].dtype)
        }

    ledger.summary = _summarize(ledger)
    return result, ledger


def apply_plan(
    df: pd.DataFrame,
    steps: list[CleaningStep],
    *,
    protected_columns: set[str] | None = None,
    table_name: str = "",
) -> tuple[pd.DataFrame, CleaningLedger]:
    """Run a typed cleaning plan end to end, returning the cleaned frame and
    the measured ledger. Steps run in order; a failing step is skipped and
    recorded, never fatal."""
    working = df.reset_index(drop=True)
    ledger = CleaningLedger(table_name=table_name, rows_before=len(working))

    for step in steps:
        working, step_ledger = apply_step(working, step, protected_columns=protected_columns)
        ledger.steps.append(step_ledger)

    ledger.rows_after = len(working)
    return working, ledger
